# Generated by Django 3.0.4 on 2020-04-02 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('group', models.CharField(choices=[('Приказ', 'Приказ'), ('Договор', 'Договор'), ('Протокол', 'Протокол'), ('Отчет', 'Отчет'), ('Акт', 'Акт'), ('Счет', 'Счет'), ('Накладная', 'Накладная'), ('Докладная записка', 'Докладная записка')], max_length=25, verbose_name='Тип')),
                ('author', models.CharField(max_length=30, verbose_name='От кого')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature', models.BooleanField()),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Подписант')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents', verbose_name='Файл')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
        ),
    ]
