# Generated by Django 3.0.4 on 2020-04-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200402_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filedocument',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
