# Generated by Django 3.0.4 on 2020-05-01 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0006_auto_20200424_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='final_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.CharField(choices=[('Поручение', 'Поручение'), ('Согласование', 'Согласование'), ('На ознакомление', 'На ознакомление'), ('На подпись', 'На подпись'), ('На регистрацию', 'На регистрацию')], default='Поручение', max_length=25, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='task',
            name='quickly',
            field=models.BooleanField(default=False, verbose_name='Срочно'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Задание передано'), ('2', 'Передан ответ'), ('3', 'Задание окончено')], default='1', max_length=20, verbose_name='Этап выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Сообщение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='documents.Task')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='FileTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/tasks', verbose_name='Файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Task')),
            ],
            options={
                'verbose_name': 'Файл задачи',
                'verbose_name_plural': 'Файлы задач',
            },
        ),
        migrations.CreateModel(
            name='FileAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/answers', verbose_name='Файл')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.TaskAnswer')),
            ],
            options={
                'verbose_name': 'Файл ответа',
                'verbose_name_plural': 'Файлы ответов',
            },
        ),
    ]
